name: Build gallery slideshow
on:
  push:
    paths:
      - 'assets/gallery/**'
      - '.github/workflows/slideshow.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: sudo apt-get update && sudo apt-get install -y imagemagick
      - name: Make slideshow.gif
        shell: bash
        run: |
          shopt -s nullglob
          mapfile -t imgs < <(ls -1v assets/gallery/*.{jpg,jpeg,png,JPG,JPEG,PNG} 2>/dev/null || true)
          if (( ${#imgs[@]} == 0 )); then echo "No images in assets/gallery"; exit 0; fi
          mkdir -p dist/gallery
          magick convert -delay 120 -loop 0 "${imgs[@]}" dist/gallery/slideshow.gif
      - uses: crazy-max/ghaction-github-pages@v4
        if: ${{ hashFiles('dist/gallery/slideshow.gif') != '' }}
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

